name: tab_generator
description: Tab Generator Studio application.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio and MIDI (Local Native Plugin)
  flutter_midi_pro:
    path: ./packages/flutter_midi_pro
  
  # File Management & Storage
  file_picker: ^8.0.0
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  path_provider: ^2.1.2
  # GPX Parsing
  archive: ^3.6.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ensure your SoundFont is properly bundled here
  assets:
    - assets/
    - assets/guitar.sf2